#+TITLE: Development Log
#+STARTUP: overview

* TODO input should not require the enter key to be pressed
* 2022-12-21
The name of this is "CLOS abuse".  Let's see if we can abuse CLOS to add traits.

* 2022-12-17
Lets line of sight and mapping mechanics.

The game should only draw parts of the map you've seen before.  And it should only draw things that are in line of sight.

Some options:
http://www.roguebasin.com/index.php/Field_of_Vision

* 2022-11-27
Let's make a real map generator.

It will create a certain number of rooms, and connect those rooms via corridoors.

The algorithm is pretty straight forward: it creates a "room" of tiles in the map.  It then connects the center of the room to the center of the previous room.

* 2022-11-24
Let's get some of the world in.  The first question is: what positioning system?

In a MUD, you usually have a graph of rooms.  You are in a single room, you see everything in your room, and 95% of all interactions are with things in your room.  You move directions to go into other rooms.

Or, we could do more of a 2d gridded map - like positioning on a piece of graph paper.  Which is more like a roguelike.

Let's go with a simple roguelike system.

Positions will be discrete - so you're at 1,1, or 3,3, etc.

Everything will only have a singular position - even very large creatures like dragons.  Nothing will be at multiple positions.

As far as collision goes, monsters will block a position, but items won't.  This won't be hard coded to monsters or items, it will just be a standard default for them which can be overridden.

We'll also have to define something to represent the player so we can move that around the map.  It's going to be as barebones as possible.

* 2022-11-22
Project started.  I wrote a very basic game loop and input parser.

The way I did the input parser isn't great.  And I'm pretty sure interning user input is a bad idea.  But, oh well.  It isn't forever.

## Version 2
At the very least, I should support listing commands.  And I don't know if it's possible with how I did things before.

So I switched it to just be a list of input handlers rather than relying on CLOS.
